const GET = {
  START: 'GET/TEST/START',
  FAIL: 'GET/TEST/FAIL',
  SUCCESS: 'GET/TEST/SUCCESS',
}

const REFRESH = {
  START: 'REFRESH/TEST/START',
  FAIL: 'REFRESH/TEST/FAIL',
  SUCCESS: 'REFRESH/TEST/SUCCESS',
}

export { GET, REFRESH }
